# -*- coding: utf-8 -*-
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms

@author: Chitru Shrestha
"""
def fib():
    result = 0
    x = 0
    y = 1
    while x <=4000000:
        if x % 2 == 0:
            result += x
        x, y = y, x + y
    return str(result)

if __name__ == "__main__":
    print(fib())